const e=JSON.parse('{"key":"v-11a37c6a","path":"/codenotes/javase/day17%20%E5%BC%82%E5%B8%B8.html","title":"day17 异常","lang":"zh-CN","frontmatter":{"title":"day17 异常","icon":"write","category":["JavaSE"],"tag":["JavaSE"],"sticky":false,"star":false,"article":true,"timeline":true,"description":"异常体系 image-20220217102836068 定义：Java的异常体系提供了一种机制，使得程序可以在遇到错误或异常时进行相应的处理，保证程序的稳定性和可靠性。程序员可以通过try-catch-finally语句来捕获和处理异常，以及通过throw和throws语句来抛出异常和声明方法可能会抛出的异常。; Error是指在程序运行期间发生的不...","head":[["meta",{"property":"og:url","content":"https://noby.site/codenotes/javase/day17%20%E5%BC%82%E5%B8%B8.html"}],["meta",{"property":"og:site_name","content":"Noby"}],["meta",{"property":"og:title","content":"day17 异常"}],["meta",{"property":"og:description","content":"异常体系 image-20220217102836068 定义：Java的异常体系提供了一种机制，使得程序可以在遇到错误或异常时进行相应的处理，保证程序的稳定性和可靠性。程序员可以通过try-catch-finally语句来捕获和处理异常，以及通过throw和throws语句来抛出异常和声明方法可能会抛出的异常。; Error是指在程序运行期间发生的不..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:updated_time","content":"2023-03-20T13:13:56.000Z"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"article:tag","content":"JavaSE"}],["meta",{"property":"article:modified_time","content":"2023-03-20T13:13:56.000Z"}]]},"excerpt":"","headers":[{"level":2,"title":"异常体系","slug":"异常体系","link":"#异常体系","children":[{"level":3,"title":"Exception","slug":"exception","link":"#exception","children":[]},{"level":3,"title":"自定义异常","slug":"自定义异常","link":"#自定义异常","children":[]}]}],"git":{"createdTime":1678720163000,"updatedTime":1679318036000,"contributors":[{"name":"noby","email":"1326981297@qq.com","commits":2}]},"readingTime":{"minutes":6.04,"words":1813},"filePathRelative":"codenotes/javase/day17 异常.md","localizedDate":"2023年3月13日"}');export{e as data};
